// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPsKW5HHdFaHw_rnpUVo7Ahf8dkD0oiE',
    appId: '1:351688174982:web:46402dd217bde92eb51007',
    messagingSenderId: '351688174982',
    projectId: 'authentication-fds',
    authDomain: 'authentication-fds.firebaseapp.com',
    storageBucket: 'authentication-fds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW0IFANHmbbxNfCgEE5f1CBX4Mq4_lzNk',
    appId: '1:351688174982:android:20da6062fd7edbe8b51007',
    messagingSenderId: '351688174982',
    projectId: 'authentication-fds',
    storageBucket: 'authentication-fds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI4RetpUHv1yZMthYxbh0-W-RKGDCU6AE',
    appId: '1:351688174982:ios:b46baf37b540fa7fb51007',
    messagingSenderId: '351688174982',
    projectId: 'authentication-fds',
    storageBucket: 'authentication-fds.firebasestorage.app',
    iosBundleId: 'com.example.funkodreamstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI4RetpUHv1yZMthYxbh0-W-RKGDCU6AE',
    appId: '1:351688174982:ios:b46baf37b540fa7fb51007',
    messagingSenderId: '351688174982',
    projectId: 'authentication-fds',
    storageBucket: 'authentication-fds.firebasestorage.app',
    iosBundleId: 'com.example.funkodreamstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwPsKW5HHdFaHw_rnpUVo7Ahf8dkD0oiE',
    appId: '1:351688174982:web:69875a76a9e8a3f9b51007',
    messagingSenderId: '351688174982',
    projectId: 'authentication-fds',
    authDomain: 'authentication-fds.firebaseapp.com',
    storageBucket: 'authentication-fds.firebasestorage.app',
  );
}
